Jinho1011/algorithm

yeonjookang/1주차/2739.구구단.py

파이썬 정규표현식을 이용하여 풀었다.
f"{n} * {i} = {i*n}"

feat: solve 2739

---

yeonjookang/1주차/17614.369.py

파이썬 문자열, 리스트, 튜플 등의 시퀀스 타입에서 특정 요소가 나타나는 횟수를 세는 데 사용되는 메서드 count를 이용하여 문자열에서 해당 문자가 얼마나 나왔는지 알아내었다.
resolve #7

feat: solve 17614

---

yeonjookang/1주차/3040.백설공주와 일곱난쟁이.py

순열: n개의 수 중 r개의 수를 순서를 중요하게 생각하며 뽑기
조합: n개의 수 중 r개의 수를 순서를 생각하지 않고 뽑기
combinations를 이용하여 풀었다.
resolve #9

feat: solve 3040

---

yeonjookang/1주차/11654.아스키코드.py

아스키코드로 변환해주는 ord 메소드이용
resolve #11

feat: solve 11654

---

yeonjookang/1주차/14681.사분면고르기.py

feat: solve 14681

---

yeonjookang/1주차/2753.윤년.py

feat: solve 2753

---

jinho1011/1712.py

feat: solve 1712

---

yeonjookang/1주차/2884.알람 시계.py

feat: solve 2884

---

yeonjookang/1주차/2438.별 찍기-1.py
yeonjookang/1주차/2439.별 찍기-2.py
yeonjookang/1주차/2444.별 찍기-7.py

print()의 개행을 없애려면 end=""를 추가한다.
반복문을 거꾸로 돌리고 싶다면, range 마지막 인자에 -1을 추가하면 된다.
resolve #22

feat: solve 2438,2439,2444

---

yeonjookang/1주차/1085.직사각형에서 탈출.py

최솟값을 구하는 파이썬 내장함수 min을 이용하여 풀었다.
resolve #24

feat: solve 1085

---

yeonjookang/1주차/3009.네 번째 점.py

직사각형의 특징을 이용하였다.
직사각형의 네 점을 조사하면, x좌표와 y좌표에 각각 중복되는 숫자들이 2개씩 있어야한다.
resolve #26

feat: solve 3009

---

yeonjookang/1주차/4153.직각삼각형.py

직각삼각형의 성질을 이용하여 풀었다.
resolve #28

feat: solve 4153

---

yeonjookang/1주차/3053.택시 가하학.py

택시 기하학의 원은 직접 점을 하나하나 찍어가면서 공식을 구했다.
택시 기하학 원 넓이 = 2*r^2
유클리드 기하학 원 넓이 = pi*r^2
resolve #30

feat: solve 3053

---

yeonjookang/1주차/10250.ACM 호텔.py

반복문으로 풀지 않고 최대한 공식을 구해보았다.
특수한 경우(H와 N이 같은 경우 등)를 주의하자.
resolve #32

feat: solve 10250

---

yeonjookang/1주차/10872.팩토리얼.py

feat: solve 10872

---

yeonjookang/1주차/2577.숫자의 개수.py

feat: solve 2577

---

yeonjookang/1주차/3052.나머지.py

중복 요소를 제거할 때에는 집합 set을 이용하자.
resolve #38

feat: solve 3052

---

yeonjookang/1주차/8958.OX퀴즈.py

feat: solve 8958

---

yeonjookang/1주차/10809.알파벳 찾기.py

아스키 코드 -> 문자 변환 : chr()
문자열에서 특정 문자 위치 찾기 : find()
resolve #44

feat: solve 10809

---

yeonjookang/1주차/2675.문자열 반복.py

feat: solve 2675

---

yeonjookang/1주차/1152.단어의 개수.py

특수한 경우(단어의 개수가 0인 경우)를 고려해야 한다.
resolve #48

feat: solve 1152

---

yeonjookang/1주차/2908.상수.py

문자열 뒤바꾸기를 str[::-1]를 이용하였다.
resolve #50

feat: solve 2908

---

yeonjookang/1주차/15552.빠른 A+B.py

input()이 아닌 sys.stdin.readline()을 사용하자.
문자열을 입력 받을 시에는 rstrip()을 꼭 사용해야 한다.
resolve #52

feat: solve 15552

---

yeonjookang/1주차/10162.전자레인지.py

몫을 구할 때
/ : 소수로
// : 정수로
나온다.
resolve #54

feat: solve 10162

---

yeonjookang/1주차/1439.뒤집기.py

특수한 경우 (문자열 마지막 문자)를 고려해줘야 한다.
resolve #56

feat: solve 1439

---

yeonjookang/1주차/1316.그룹단어 체커.py

feat: solve 1316

---

yeonjookang/1주차/2941.크로아티아 알파벳.py

발생할 수 있는 예외들을 모두 처리해주자.
resolve #60

feat: solve 2941

---

jinho1011/1158.py
jinho1011/17614.py
jinho1011/18258.py

solve 1158, 11258

---

yeonjookang/1주차/5618.공약수.py

feat: solve 5618

---

yeonjookang/1주차/4619.루트.py

특수 경우 (B==1, N==1)을 고려하자.
resolve #64

feat: solve 4619

---

yeonjookang/1주차/2309.일곱난쟁이.py

리스트 정렬: sort(), reverse()
resolve #66

feat: solve 2309

---

yeonjookang/1주차/2798.블랙잭.py

feat: solve 2798

---

yeonjookang/1주차/2231.분해합.py

리스트의 합을 구하려면 map(int,리스트)를 이용하자! -> 문자들을 숫자로 바꿔줌
resolve #70

feat: solve 2231

---

.gitignore
ro-el-c/BJ_17614.py
ro-el-c/BJ_2309.py
ro-el-c/BJ_2798.py
ro-el-c/BJ_4619.py
ro-el-c/README.md

Brute Force
BOJ 2309 / 2798 / 4619 / 17614 with `Python`

feat: ro-el 2309, 2798, 4619, 17614

---

yeonjookang/1주차/10448.유레카 이론.py

중복 조합 이용
combination_with_replacement
resolve #74

feat: solve 10448

---

yeonjookang/1주차/13410.거꾸로 구구단.py

문자열은 리스트가 아니다!
문자열 -> 리스트 : list(문자열)
리스트 -> 문자열 : ''.join(리스트)
리스트 거꾸로 변환 : [::-1]
resolve #76

feat: solve 13410

---

yeonjookang/1주차/18312.시각.py
yeonjookang/1주차/2851.슈퍼 마리오.py

feat: fail 18312

---

jinho1011/2503.py

가능한 정답 미리 순열로 생성해두고 조건 안맞으면 지움

feat: solve 2503

---

jinho1011/18512.py

feat: 18512

---

yeonjookang/1주차/18512.점프 점프.py

feat: solve 18512

---

yeonjookang/1주차/1145.적어도 대부분의 배수.py

feat: solve 1145

---

yeonjookang/1주차/1526.가장 큰 금민수.py

feat: solve 1526

---

yeonjookang/1주차/14914.사과와 바나나 나눠주기.py

feat: solve 14914

---

jinho1011/4673.py

feat: solve 4673

---

yeonjookang/1주차/11170.0의 개수.py
yeonjookang/1주차/4673.셀프 넘버.py

feat: solve 11170

---

yeonjookang/1주차/7568.덩치.py

feat: solve 7568

---

jinho1011/1018.py
jinho1011/1436.py

feat: solve 1018, 1436

---

yeonjookang/1주차/1018.체스판 다시 칠하기.py

파이썬 2차원 배열 만드는 법
[ [0 for in range(N)] for in range(M) ] 
배열을 초기화할 때 조건문도 넣을 수 있다.
[ [0 if a==0 else 1 for in range(N)] for in range(M) ] 
resolve #97

feat: solve 1018

---

yeonjookang/1주차/1065.한수.py

feat: solve 1065

---

yeonjookang/1주차/1436.영화감독 숌.py

브루트포스로 1부터 666이 들어있는지 확인하면 되는 문제
resolve #99

feat: solve 1436

---

yeonjookang/2주차/9012.괄호.py

feat: solve 9012

---

yeonjookang/2주차/1835.카드.py

문제 이해가 안돼서 답을 살~짝 봤다!
하던 순서의 반대로 진행하면 된다!
resolve #110

feat: solve 1835

---

yeonjookang/2주차/#2주차 내용정리.md
yeonjookang/2주차/23757.아이들과 선물상자.py

우선순위 큐 heapq를 이용!
heapify()를 이용하려고 했지만 최대힙이 필요했기 때문에 반복문으로 하나하나 - 달아서 append() 해줌 
resolve #112

feat: solve 23757

---

yeonjookang/2주차/4158.CD.py

feat: solve 4158

---

yeonjookang/2주차/7785.회사에 있는 사람.py

feat: solve 7785

---

yeonjookang/2주차/1021.회전하는 큐.py

경우의 수를 잘 따지자.
양방향 큐는 덱을 사용하자
resolve #122

feat: solve 1021

---

yeonjookang/2주차/1158.요세푸스 문제.py

feat: solve 1158

---

yeonjookang/2주차/3986.좋은 단어.py

feat: solve 3986

---

yeonjookang/2주차/1302.베스트셀러.py

딕셔너리를 이용하여 풀었다.
딕셔너리를 반복문으로 넣으면 key값을 얻을 수 있다.
딕셔너리는 value 값은 얻기 힘들지만, key 값은 얻기 쉽다.
resolve #134

feat: solve 1302

---

yeonjookang/2주차/1874.스택 수열.py

feat: solve 1874

---

yeonjookang/2주차/10799.쇠막대기.py

feat: solve 10799

---

jinho1011/2346.py

feat: solve 2346

---

yeonjookang/2주차/1966번. 프린터 큐.py

feat: solve 1966

---

yeonjookang/2주차/5397.키로거.py

리스트의 delete문과 insert문을 사용했더니 시간 초과가 났다.
구글에서 찾아보니 스택 두 개를 사용해서 커서를 기준으로 오른쪽 문자는 sub 스택에, 왼쪽 문자는 pwd 스택에 넣어 풀었다.
resolve #153

feat: solve 5397

---

yeonjookang/2주차/1935.후위 표기식2.py

feat: solve 1935

---

yeonjookang/2주차/14235.크리스마스 선물.py

우선순위 관련된 문제라면 우선순위 큐를 이용하자.
resolve #157

feat: solve 14235

---

yeonjookang/3주차/2178.미로 탐색-1차.py
yeonjookang/3주차/2178.미로 탐색.py

최단 거리 탐색 ->bfs 이용!
bfs는 큐와 방문 체크 2차원 배열, map 2차원 배열을 이용한다!
resolve #164

feat: solve 2178

---

yeonjookang/3주차/1182.부분 수열의 합.py

feat: solve 1182

---

yeonjookang/3주차/1743.음식물 피하기.py

dfs로 먼저 풀다가 2차원 배열의 복잡함 때문에 bfs도 바꿨다.
미로찾기의 bfs를 응용하여 풀었다.
resolve #168

feat: solve 14426

---

yeonjookang/3주차/2667.단지번호 붙이기.py

feat: solve 2667

---

yeonjookang/3주차/2583.영역 구하기.py

feat: solve 2583

---

yeonjookang/3주차/2468.안전 영역.py

feat: solve 2468

---

ro-el-c/BJ_2884.py
ro-el-c/BJ_3009.py
ro-el-c/BJ_3040.py
ro-el-c/BJ_3053.py

feat: 1주차 완료

---

yeonjookang/자료구조/10828.스택.py

파이썬에서 제공하는 스택 자료구조인 리스트를 이용해 풀었습니다.
파이썬 함수에서 전역 변수를 사용하기 위해서는 global 선언이 필요하다는 것을 배웠습니다.

solve: 10828 자료구조(스택) 문제 해결

---

yeonjookang/자료구조/1093.단어 뒤집기.py

자료구조 스택으로 해결
sys.stdin.readline()으로 받으면 마지막에 "\n"이 같이 들어오는 것에 주의.

solve: 1093번 자료구조 스택으로 해결

---

yeonjookang/자료구조/1406.에디터.py

스택 자료구조를 이용해 풀었습니다.
마지막에 두 스택을 합칠 때, 오른쪽 스택은 역순으로 합쳐주어야 한다는 것에서 오류가 났었습니다.
문자열와 리스트로 서로 어떻게 변환하는지 알았습니다.

solve: 1406번 스택 자료구조 이용하여 해결

---

yeonjookang/자료구조/10845.큐.py

자료구조 덱을 이용해서 해결.
리스트는 스택 구조이고, 덱은 양 옆에서 뺐다 꺼낼 수 있는 구조로 상황에 맞게 사용하자.
추가적으로 덱은 double linked list로 구현되어있어 appendleft와 popleft의 시간복잡도가 O(1)이다.!!
(리스트의 첫번째 원소 추가/삭제 시간복잡도는 O(N)..)

solve: 10845번

---

yeonjookang/자료구조/17413.단어뒤집기2.py

solve: 17413번

---

somin-jeong/알고리즘 기초 1-1/자료구조/10828 스택.py

feat: solve 10828

---

somin-jeong/알고리즘 기초 1-1/자료구조/9093 단어뒤집기.py

- 파이썬 리스트를 활용해서 스택 구현
- 리스트에 넣고 pop하는 일을 한 문장의 단어 개수만큼 반복

feat: solve 9093

---

somin-jeong/알고리즘 기초 1-1/자료구조/1874 스택수열.py

- 파이썬 리스트 활용해서 스택 구현
- 풀이 과정
- intList에 입력 받은 숫자들 넣음
- stack에 값들 push하고, intList에 있는 숫자에 따라 pop 수행
- printList에 출력할 + 또는 - 넣음

feat: solve 1874 (시간 초과)
